import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Text } from "../components/Typography";
import { StateView } from "../components/state-view";
import type { LongRouteBooking } from "../long-routes/types";
import { formatDateTime, formatNad } from "../long-routes/data";
import type { BookingsStackParamList } from "../navigation/types";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { colors, radii, shadow } from "../theme";

type Props = NativeStackScreenProps<BookingsStackParamList, "BookingsHome">;
type Tab = "UPCOMING" | "COMPLETED" | "CANCELLED";

export default function BookingsScreen({ navigation }: Props) {
  const { idToken } = useAuth(); const [bookings, setBookings] = useState<LongRouteBooking[]>([]); const [tab, setTab] = useState<Tab>("UPCOMING"); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!idToken) return; try { setBookings(await api.listLongRouteBookings(idToken)); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "Bookings could not be loaded"); } }, [idToken]);
  useEffect(() => { void load().finally(() => setLoading(false)); }, [load]);
  const filtered = useMemo(() => bookings.filter((booking) => tab === "CANCELLED" ? ["CANCELLED", "REFUNDED"].includes(booking.bookingStatus) : tab === "COMPLETED" ? ["COMPLETED", "MISSED"].includes(booking.bookingStatus) : !["CANCELLED", "REFUNDED", "COMPLETED", "MISSED"].includes(booking.bookingStatus)), [bookings, tab]);
  if (loading) return <View style={styles.centered}><ActivityIndicator color={colors.success} /></View>;
  if (error) return <StateView title="Bookings unavailable" message={error} actionLabel="Try again" onAction={() => { setLoading(true); void load().finally(() => setLoading(false)); }} />;
  return <FlatList style={styles.screen} contentContainerStyle={styles.content} contentInsetAdjustmentBehavior="automatic" data={filtered} keyExtractor={(item) => item.bookingId} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load().finally(() => setRefreshing(false)); }} />} ListHeaderComponent={<View style={styles.header}><Text style={styles.title}>My bookings</Text><Text style={styles.subtitle}>Tickets, payments, cancellations, and trip updates</Text><View style={styles.tabs}>{(["UPCOMING", "COMPLETED", "CANCELLED"] as Tab[]).map((item) => <Pressable key={item} style={[styles.tab, tab === item && styles.tabActive]} onPress={() => setTab(item)}><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{item.charAt(0) + item.slice(1).toLowerCase()}</Text></Pressable>)}</View></View>} ListEmptyComponent={<StateView title={`No ${tab.toLowerCase()} bookings`} message={tab === "UPCOMING" ? "Your confirmed long-route trips will appear here." : "There are no bookings in this section."} />} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => navigation.navigate("BookingDetail", { bookingId: item.bookingId })}><View style={styles.cardHeader}><View style={{ flex: 1 }}><Text style={styles.route}>{item.tripSnapshot.departureTown} to {item.tripSnapshot.destinationTown}</Text><Text style={styles.meta}>{formatDateTime(item.tripSnapshot.departureDateTime)}</Text></View><Text style={styles.status}>{item.bookingStatus.replace(/_/g, " ")}</Text></View><View style={styles.details}><Detail label="Seats" value={item.seatNumbers.join(", ")} /><Detail label="Operator" value={item.tripSnapshot.operatorName} /><Detail label="Total" value={formatNad(item.totalAmount)} /></View><View style={styles.footer}><Text style={styles.reference} selectable>{item.bookingReference}</Text><Text style={styles.payment}>{item.paymentStatus.replace(/_/g, " ")}</Text></View></Pressable>} />;
}
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.wash }, centered: { flex: 1, alignItems: "center", justifyContent: "center" }, content: { padding: 16, gap: 12, paddingBottom: 30 }, header: { gap: 8, paddingBottom: 4 }, title: { color: colors.ink, fontSize: 25, fontWeight: "900" }, subtitle: { color: colors.muted, fontSize: 11 }, tabs: { flexDirection: "row", backgroundColor: colors.surface, borderRadius: radii.md, padding: 4, borderWidth: 1, borderColor: colors.line, marginTop: 6 }, tab: { flex: 1, minHeight: 38, alignItems: "center", justifyContent: "center", borderRadius: radii.sm }, tabActive: { backgroundColor: colors.navy }, tabText: { color: colors.muted, fontSize: 10, fontWeight: "800" }, tabTextActive: { color: colors.surface }, card: { backgroundColor: colors.surface, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.line, padding: 15, gap: 13, ...shadow }, cardHeader: { flexDirection: "row", gap: 10 }, route: { color: colors.ink, fontSize: 15, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 10, marginTop: 3 }, status: { color: colors.success, backgroundColor: colors.successWash, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6, overflow: "hidden", fontSize: 7, fontWeight: "900" }, details: { flexDirection: "row", gap: 10 }, detail: { flex: 1, gap: 3 }, detailLabel: { color: colors.muted, fontSize: 8 }, detailValue: { color: colors.ink, fontSize: 10, fontWeight: "800" }, footer: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 10 }, reference: { color: colors.navy, fontSize: 10, fontWeight: "900" }, payment: { color: colors.text, fontSize: 8, fontWeight: "800" } });
