import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Text, TextInput } from "../../components/Typography";
import { StateView } from "../../components/state-view";
import type { PassengerDetails } from "../../long-routes/types";
import type { DriverStackParamList } from "../../navigation/types";
import { api } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";
import { colors, radii, shadow } from "../../theme";

type Props = NativeStackScreenProps<DriverStackParamList, "PassengerManifest">;
type ManifestPassenger = PassengerDetails & { bookingId: string; bookingReference: string; paymentStatus: string; checkInStatus: string };

export default function PassengerManifestScreen({ route }: Props) {
  const { idToken } = useAuth(); const [passengers, setPassengers] = useState<ManifestPassenger[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!idToken) return; try { const result = await api.getManifest(route.params.tripId, idToken); setPassengers(result.passengers); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "Manifest could not be loaded"); } }, [idToken, route.params.tripId]);
  useEffect(() => { void load().finally(() => setLoading(false)); }, [load]);
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); return passengers.filter((passenger) => !value || [passenger.fullName, passenger.phoneNumber, passenger.bookingReference, passenger.seatNumber].some((field) => String(field).toLowerCase().includes(value))); }, [passengers, query]);
  const checkIn = async (passenger: ManifestPassenger) => { if (!idToken) return; try { await api.checkInPassenger(passenger.bookingId, passenger.seatNumber, true, idToken); await load(); Alert.alert("Passenger checked in", `Seat ${passenger.seatNumber} and luggage are marked ready.`); } catch (err) { Alert.alert("Check-in warning", err instanceof Error ? err.message : "This ticket may already be checked in."); } };
  const confirmPayment = async (passenger: ManifestPassenger) => { if (!idToken) return; try { await api.confirmPayment(passenger.bookingId, idToken); await load(); Alert.alert("Payment confirmed", `Booking ${passenger.bookingReference} is now marked paid.`); } catch (err) { Alert.alert("Payment warning", err instanceof Error ? err.message : "Payment could not be confirmed."); } };
  if (loading) return <View style={styles.centered}><ActivityIndicator color={colors.success} /></View>;
  if (error) return <StateView title="Manifest unavailable" message={error} actionLabel="Try again" onAction={() => { setLoading(true); void load().finally(() => setLoading(false)); }} />;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} contentInsetAdjustmentBehavior="automatic" keyboardShouldPersistTaps="handled"><View><Text style={styles.title}>Passenger manifest</Text><Text style={styles.subtitle}>{passengers.length} booked passenger{passengers.length === 1 ? "" : "s"} • available offline after loading</Text></View><TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search name, phone, reference, or seat" placeholderTextColor={colors.muted} />{filtered.length ? filtered.map((passenger) => <View key={`${passenger.bookingId}-${passenger.seatNumber}`} style={styles.card}><View style={styles.cardHeader}><View style={styles.seat}><Text style={styles.seatLabel}>SEAT</Text><Text style={styles.seatNumber}>{passenger.seatNumber}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{passenger.fullName}</Text><Text style={styles.meta} selectable>{passenger.phoneNumber} • {passenger.bookingReference}</Text></View><Text style={[styles.checkStatus, passenger.checkInStatus === "CHECKED_IN" && styles.checked]}>{passenger.checkInStatus.replace(/_/g, " ")}</Text></View><View style={styles.details}><Detail label="Payment" value={passenger.paymentStatus.replace(/_/g, " ")} /><Detail label="Luggage" value={passenger.luggageDetails} /><Detail label="Assistance" value={passenger.specialAssistance} /><Detail label="Emergency" value={passenger.emergencyContact} /></View>{passenger.paymentStatus !== "PAID" ? <Pressable style={styles.paymentButton} onPress={() => void confirmPayment(passenger)}><Text style={styles.paymentButtonText}>Confirm passenger payment</Text></Pressable> : null}<Pressable style={[styles.button, passenger.checkInStatus === "CHECKED_IN" && styles.disabled]} disabled={passenger.checkInStatus === "CHECKED_IN"} onPress={() => void checkIn(passenger)}><Text style={styles.buttonText}>{passenger.checkInStatus === "CHECKED_IN" ? "Already checked in" : "Check in passenger & luggage"}</Text></Pressable></View>) : <StateView title="No passengers found" message={passengers.length ? "Try a different search." : "Booked passengers will appear here with operational details."} />}</ScrollView>;
}
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue} selectable>{value || "Not provided"}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.wash }, centered: { flex: 1, alignItems: "center", justifyContent: "center" }, content: { padding: 18, gap: 12, paddingBottom: 36 }, title: { color: colors.ink, fontSize: 23, fontWeight: "900" }, subtitle: { color: colors.muted, fontSize: 11, marginTop: 3 }, search: { minHeight: 50, borderRadius: radii.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, paddingHorizontal: 14, color: colors.ink, fontSize: 13 }, card: { backgroundColor: colors.surface, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 12, ...shadow }, cardHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, seat: { width: 48, height: 48, borderRadius: 13, backgroundColor: colors.navy, alignItems: "center", justifyContent: "center" }, seatLabel: { color: "#aebfd1", fontSize: 6, fontWeight: "900" }, seatNumber: { color: colors.surface, fontSize: 16, fontWeight: "900" }, name: { color: colors.ink, fontSize: 14, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 9, marginTop: 3 }, checkStatus: { color: colors.warning, backgroundColor: colors.warningWash, borderRadius: 7, paddingHorizontal: 7, paddingVertical: 5, overflow: "hidden", fontSize: 7, fontWeight: "900", maxWidth: 80, textAlign: "center" }, checked: { color: colors.success, backgroundColor: colors.successWash }, details: { gap: 7 }, detail: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, detailLabel: { color: colors.muted, fontSize: 9 }, detailValue: { flex: 1, color: colors.text, fontSize: 9, fontWeight: "700", textAlign: "right" }, paymentButton: { minHeight: 42, borderWidth: 1, borderColor: colors.navy, borderRadius: radii.md, alignItems: "center", justifyContent: "center" }, paymentButtonText: { color: colors.navy, fontSize: 10, fontWeight: "900" }, button: { minHeight: 44, backgroundColor: colors.success, borderRadius: radii.md, alignItems: "center", justifyContent: "center" }, buttonText: { color: colors.navy, fontSize: 11, fontWeight: "900" }, disabled: { opacity: 0.45 } });
